name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Simple Test Job
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[dev,anthropic,sentencepiece,optimum]'
        pip install flake8 black mypy
    
    - name: Run basic imports
      run: |
        python3 -c "import src.metrics; print('Metrics import successful')"
        python3 -c "import src.stats; print('Stats import successful')"
        python3 -c "import src.visualization; print('Visualization import successful')"
    
    - name: Run pytest
      run: |
        python3 -m pytest tests/ -v --tb=short

  # Code Quality
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black mypy
    
    - name: Run flake8
      run: |
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics || true
    
    - name: Run black check
      run: |
        black --check src/ tests/ || true
    
    - name: Run mypy
      run: |
        mypy src/ --ignore-missing-imports || true